permissions:
  # admin 以外にグループが必要であれば、同じネストに書く
  admin:
    # model 毎に権限設定可能
    home: [read, write, delete]
    users: [read, write, delete]
  normal:
    home: [read, write, delete]
    users: [read, write, delete]
